apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          ports:
            - containerPort: 8080
          args: ["start-dev", "--import-realm", "--proxy=edge"]
          env:
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  key: DB_VENDOR
                  name: keycloak-realm-config
            - name: DB_ADDR
              valueFrom:
                configMapKeyRef:
                  key: DB_ADDR
                  name: keycloak-realm-config
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: keycloak-realm-config
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: keycloak-realm-config
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: keycloak-secrets
            - name: KEYCLOAK_USER
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_USER
                  name: keycloak-realm-config
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_ADMIN
                  name: keycloak-realm-config
            - name: KEYCLOAK_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_USER_PASSWORD
                  name: keycloak-secrets
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_ADMIN_PASSWORD
                  name: keycloak-secrets
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: local.jsbms.keycloak
            - name: KC_HOSTNAME_STRICT
              value: "true"
            - name: KC_PROXY
              value: "edge"
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
data:
  DB_PASSWORD: cGFzc3dvcmQ=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
  KEYCLOAK_USER_PASSWORD: YWRtaW4=
kind: Secret
metadata:
  name: keycloak-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  DB_VENDOR: "MYSQL"
  DB_ADDR: "mysql"
  DB_DATABASE: "keycloak"
  DB_USER: "keycloak"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_USER: "admin"